# Generated by Django 3.2.12 on 2022-02-28 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pluto', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
